start_date = 'Start date'
end_date = 'End date'
pm10 = 'PM 10'
pm25 = 'PM 2.5'
NO = 'NO'
NO2 = 'NO2'
NOXasNO = 'NOX as NO'

p1 = 'P1'
p2 = 'P2'
sds_pm10 = 'SDS_P1'
sds_pm25 = 'SDS_P2'


id = 'id'
station_id = 'station_id'
sensor = 'sensor'
sensor_id = 'sensor_id'
sensor_type = 'sensor_type'
sensor_type_id = 'sensor_type_id'
sensor_name = 'sensor_name'
name = 'name'
indoor = 'indoor'
location = 'location'
timestamp = 'timestamp'
latitude ='latitude'
longitude = 'longitude'
info_dict = 'info_dict'
distance = 'distance'
